### ISSUE TITLE
Align BSD coreutils with GNU coreutils: the re-en-flaggening

### ISSUE THREAD

**Issue by christhekeele** [knockrentals/lambda-builder#1]
This builder was developed on an Ubuntu system. Oops.

Currently `make check` reports if expected `bash` builtins are available, and if all other expected commands:

- exist on the current `bash` session's `$PATH`
- have executable permissions

Linux computers can choke on this during bootstrapping if you don't `chmod +x ./bin/**/*` first, because it refuses to accept `git` files permissions on clone. This is (or will soon be) well-documented in the README.md.

If your system doesn't support `bash`, then god help you in executing these commands. On the other hand, system support doesn't matter in the slightest when it comes down to blow-by-blow feature parity with non-builtin command *flag* support.

`knockrentals/lambda-builder` strives to support all `*nix`es, hence its ability to report on availability of all anticipated required executables. But because I'm that one guy who won't get a Mac like everyone else, local testing ran in an assumed GNU coreutils for maximum command-compat. But not all 'standard' command-line executables accept the same flags as GNU variants--namely, Mac's BSD coreutils origins.

Reported by @mesknock, this will be a thread to discuss full `*nix` compatibility support.

**Comment by mesknock** [comment]
I think there are a couple of ways we can approach this. 

First would be to provide the necessary instructions for shoring up the `coreutils` and other command line utilities on macOS to match the expected GNU version. I have started documenting this in a branch already, but it can be a little tedious and could possibly break other things on macs that rely on the base versions, though I have not encountered that yet myself.

Another option would be to define all the various utilities used as environment variables, and allow the consumers to define what tool they want to use. For instance, we would define `FIND ?= /usr/bin/find` and then users on macOS could override that by `export FIND = /usr/local/bin/find` before invoking `make`. Unfortunately this is also pretty tedious and might be a bit more portability than we actually need.

**Comment by christhekeele** [comment]
I think the latter is `make` best practice but I too am disinclined to it. I worry about the former breaking things though not *too* much.

I think the only things we would need to ensure parity on are:

```bash
# Portable bash commands all tooling assumes exists
CHECK_COMMANDS += cat cp curl find 
CHECK_COMMANDS += mkdir sed touch
```

Our usage of `cat`, `curl`, `mkdir`, `sed`, and `touch` are fairly innocuous, and the only `cp` incompatibility was that unnecessary `u` flag I was using. I think that mostly leaves `find` to iron out.

**Comment by mesknock** [comment]
That makes sense to me. I will try backing out the adjustments I have made and capture the errors I was encountering. Once I get all those collected I'll throw them up here so we can work through them.

**Comment by mesknock** [comment]
For `find`, it looks like the BSD version does not support the `-printf` flag. First thing that comes to mind in terms is using `-print0` and `xargs`, as I have done [here](https://github.com/knockrentals/lambda-builder/compare/feature/ms-add-macos-prereqs).

As you can see I originally attempted to use `-print0 | xargs -0 -n 1 basename`, but this strips off the path. Using `-print` seems to preserve the entire directory structure (at least on macOS).

**Comment by christhekeele** [comment]
I was just trying to be lazy and not pipe `find` into another command, but whatever `sed`ing or what not we have to do for parity is fine.

**Comment by mesknock** [comment]
Took a stab at trying to make the `date` invocations portable. Unfortunately we can't fully preserve the timezone format supported by GNU date, but we can get pretty close: https://github.com/knockrentals/lambda-builder/commit/281b25f3cb8627d286f17cf6a6517ee25ae265b7

**Comment by christhekeele** [comment]
@mesknock I think we can close this with your implementation of #6, feel free to re-open if there's more to discuss
